---

- user: ec2-user
  hosts: all
  tasks:

    # print diff of latest values and our values

    - name: Gather env datadog tag
      set_fact:
        datadog_env: "{{ env }}"

    - name: Translate prod to ops var
      set_fact:
        datadog_env: ops
      when: datadog_env == "prod"

    - name: Generate Config
      template: 
        src: templates/datadog/datadog_values.yml.j2
        dest: /home/ec2-user/datadog_values.yml
    
    # helm apply

    - name: Get secret
      command: get-datadog-api-key
      register: datadog_api_key

    - name: Helm repo update
      command: helm repo update

    - name: Helm deploy
      shell: helm upgrade --install datadog datadog/datadog -f /home/ec2-user/datadog_values.yml --set datadog.apiKey={{ datadog_api_key.stdout }} --create-namespace -n datadog
      args:
        chdir: /home/ec2-user/

