---

- user: ec2-user
  hosts: all
  tasks:

    # print diff of latest values and our values


    - name: Generate Config
      template: 
        src: templates/datadog/datadog_values.yml.j2
        dest: ./datadog_values.yml
    
    # helm apply

    - name: Get secret
      command: get-datadog-api-key
      register: datadog_api_key

    - name: Helm deploy
      # shell: helm upgrade —install datadog datadog/datadog -f /home/ec2-user/datadog_values.yml —set datadog.apiKey={{ lookup(‘amazon.aws.aws_secret’, datadog_api_key_id, region=‘us-east-1’, version_stage=‘AWSCURRENT’) }} —create-namespace -n datadog
      shell: helm upgrade —install datadog datadog/datadog -f /home/ec2-user/datadog_values.yml —set datadog.apiKey={{ datadog_api_key.stdout }} —create-namespace -n datadog
      args:
        chdir: /home/ec2-user/


