---

- user: ec2-user
  hosts: all
  tasks:

    # print diff of latest values and our values

    - name: Gather env datadog tag
      set_fact:
        datadog_env: "{{ env }}"

    - name: Translate prod to ops var
      set_fact:
        datadog_env: ops
      when: datadog_env == "prod"

    - name: Generate Config
      template: 
        src: templates/datadog/datadog_values.yml.j2
        dest: /home/ec2-user/jupyterhub-deploy/datadog/datadog_values_ansible.yml
    
    - name: Helm deploy
      shell: deploy-datadog datadog_values_ansible.yml
      args:
        chdir: /home/ec2-user/

